version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the source code directory into the container.
      # This enables live-reloading during development.
      - ./src:/app
      - ./.env:/app/.env
      - ./pyproject.toml:/pyproject.toml
      - ./pytest.ini:/pytest.ini
    # Override the CMD for development to enable --reload functionality
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload